services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-tour
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server --loglevel notice --save 60 1 --appendonly yes --appendfsync
      everysec --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-tour-ui
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:5540",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-tour-app
    restart: unless-stopped
    environment:
      REDIS_ADDR: redis:6379
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  redis-data:

